<?xml version="1.0" encoding="utf-8"?>
<xsd:schema
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.regione.veneto.it/schemas/2012/Pagamenti/Ente/"
  xmlns="http://www.regione.veneto.it/schemas/2012/Pagamenti/Ente/"
  elementFormDefault="qualified" attributeFormDefault="unqualified"
  version="6.0.1">

  <xsd:annotation>
    <xsd:documentation>Dovuti e Pagati</xsd:documentation>
    <xsd:documentation>XSD Dovuti/Pagati</xsd:documentation>
  </xsd:annotation>

  <xsd:simpleType name="stText64">
    <xsd:restriction base="xsd:string">
      <xsd:minLength value="1" />
      <xsd:maxLength value="64" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="stImportoPositivo">
    <xsd:restriction base="xsd:decimal">
      <xsd:minInclusive value="0.01" /> <!-- force to set value different from 0.-->
      <xsd:maxInclusive value="999999999.99" />
      <xsd:pattern value="\d+\.\d{2}" />
    </xsd:restriction>
  </xsd:simpleType>



  <!-- Define the bilancio element -->
  <xsd:element name="bilancio" type="ctBilancio">
    <xsd:annotation>
      <xsd:documentation>Bilancio</xsd:documentation>
    </xsd:annotation>
  </xsd:element>

  <!-- Complex type for bilancio -->
  <xsd:complexType name="ctBilancio">
    <xsd:sequence>
      <xsd:element name="capitolo" type="ctCapitolo" minOccurs="1"  maxOccurs="unbounded">
        <xsd:annotation>
          <xsd:documentation>Aggregazione di "capitolo"
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <!-- Complex type for capitolo -->
  <xsd:complexType name="ctCapitolo">
    <xsd:sequence>
      <xsd:element name="codCapitolo" type="stText64" minOccurs="1">
        <xsd:annotation>
          <xsd:documentation>Codice del capitolo, obbligatorio
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="codUfficio" type="stText64" minOccurs="0">
        <xsd:annotation>
          <xsd:documentation>Codice dell' ufficio da cui il capitolo dipende, non obbligatorio
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="accertamento" type="ctAccertamento" minOccurs="1" maxOccurs="unbounded">
        <xsd:annotation>
          <xsd:documentation>Aggregazione di "accertamento"
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <!-- Complex type for accertamento -->
  <xsd:complexType name="ctAccertamento">
    <xsd:sequence>
      <xsd:element name="codAccertamento" type="stText64" minOccurs="0">
        <xsd:annotation>
          <xsd:documentation>Codice dell' accertamento obbligatorio, al limite vuoto
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="importo" type="stImportoPositivo" minOccurs="1">
        <xsd:annotation>
          <xsd:documentation>Importo dell' accertamento. Campo numerico (due cifre per la parte decimale,
            il separatore dei centesimi è il punto “.”), indicante l’importo
            relativo alla somma da
            versare. Deve essere diverso da “0.00”.
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

</xsd:schema>
