package it.gov.pagopa.pu.classification.util;

public class ErrorCodeConstants {
  private ErrorCodeConstants() {}

  public static final String ERROR_CODE_TOO_MANY_EXPORTED_RECORDS = "TOO_MANY_EXPORTED_RECORDS";

  public static final String ERROR_CODE_INVALID_INSTALLMENT = "INVALID_INSTALLMENT";
  public static final String ERROR_CODE_INVALID_IUD = "INVALID_IUD";

  public static final String ERROR_CODE_ORGANIZATION_NOT_FOUND = "ORGANIZATION_NOT_FOUND";

  public static final String ERROR_CODE_CLASSIFICATION_NOT_FOUND = "CLASSIFICATION_NOT_FOUND";
  public static final String ERROR_CODE_RECEIPT_NOT_FOUND = "RECEIPT_NOT_FOUND";
  public static final String ERROR_CODE_DEBT_POSITION_TYPE_ORG_NOT_FOUND = "DEBT_POSITION_TYPE_ORG_NOT_FOUND";

  public static final String ERROR_CODE_ASSESSMENT_NOT_FOUND = "ASSESSMENT_NOT_FOUND";
  public static final String ERROR_CODE_ASSESSMENT_ALREADY_EXISTS = "ASSESSMENT_ALREADY_EXISTS";

  public static final String ERROR_CODE_ASSESSMENT_REGISTRY_NOT_FOUND = "ASSESSMENT_REGISTRY_NOT_FOUND";
  public static final String ERROR_CODE_INVALID_ASSESSMENT_REGISTRY = "INVALID_ASSESSMENT_REGISTRY";
  public static final String ERROR_CODE_TOO_MANY_ASSESSMENT_REGISTRY = "TOO_MANY_ASSESSMENT_REGISTRY";

  public static final String ERROR_CODE_BALANCE_MARSHALLING_ERROR = "BALANCE_MARSHALLING_ERROR";
  public static final String ERROR_CODE_BALANCE_CALCULATION_ERROR = "BALANCE_CALCULATION_ERROR";
  public static final String ERROR_CODE_INVALID_BALANCE_AMOUNT = "INVALID_BALANCE_AMOUNT";
  public static final String ERROR_CODE_BALANCE_PERCENTAGE_INCOMPLETE = "BALANCE_PERCENTAGE_INCOMPLETE";

  public static final String ERROR_CODE_XML_MARSHALLING_ERROR = "XML_MARSHALLING_ERROR";
  public static final String ERROR_CODE_XML_UNMARSHALLING_ERROR = "XML_UNMARSHALLING_ERROR";
}
